### ISSUE TITLE
有关浏览器选择

### ISSUE THREAD

**Issue by harryisfish** [xxcosmos/buy_pig_plan_python#5]
是否只支持 Firefox ？
可否支持 Chrome ？

**Comment by xxcosmos** [comment]
支持Chrome，更换方法请仔细阅读README



________________________________
寄件者: tymon42 <notifications@github.com>
寄件日期: Monday, March 30, 2020 1:44:45 PM
收件者: xxcosmos/buy_pig_plan_python <buy_pig_plan_python@noreply.github.com>
副本: Subscribed <subscribed@noreply.github.com>
主旨: [xxcosmos/buy_pig_plan_python] 有关浏览器选择 (#5)


是否只支持 Firefox ？
可否支持 Chrome ？

―

**Comment by harryisfish** [comment]
明白了，谢谢！
